"""expand campaign fields

Revision ID: 524c43f3dcd1
Revises: 497eaa5970f7
Create Date: 2026-09-05 22:07:41.223677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524c43f3dcd1'
down_revision: Union[str, Sequence[str], None] = '497eaa5970f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('preview_text', sa.String(length=300), nullable=True))
    op.add_column('campaigns', sa.Column('cta_text', sa.String(length=150), nullable=True))
    op.add_column('campaigns', sa.Column('cta_url', sa.String(length=500), nullable=True))
    op.add_column('campaigns', sa.Column('audience_description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'audience_description')
    op.drop_column('campaigns', 'cta_url')
    op.drop_column('campaigns', 'cta_text')
    op.drop_column('campaigns', 'preview_text')
    # ### end Alembic commands ###
