"""add campaign delivery tracking

Revision ID: eb1ba0102890
Revises: 524c43f3dcd1
Create Date: 2026-09-05 22:52:19.442998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1ba0102890'
down_revision: Union[str, Sequence[str], None] = '524c43f3dcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'subscriber_id', name='uq_campaign_delivery_campaign_subscriber')
    )
    op.create_index(op.f('ix_campaign_deliveries_campaign_id'), 'campaign_deliveries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_deliveries_id'), 'campaign_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_deliveries_provider_message_id'), 'campaign_deliveries', ['provider_message_id'], unique=True)
    op.create_index(op.f('ix_campaign_deliveries_status'), 'campaign_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_deliveries_subscriber_id'), 'campaign_deliveries', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_deliveries_subscriber_id'), table_name='campaign_deliveries')
    op.drop_index(op.f('ix_campaign_deliveries_status'), table_name='campaign_deliveries')
    op.drop_index(op.f('ix_campaign_deliveries_provider_message_id'), table_name='campaign_deliveries')
    op.drop_index(op.f('ix_campaign_deliveries_id'), table_name='campaign_deliveries')
    op.drop_index(op.f('ix_campaign_deliveries_campaign_id'), table_name='campaign_deliveries')
    op.drop_table('campaign_deliveries')
    # ### end Alembic commands ###
